version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p1backend
    ports:
      - "4444:4444"  # map host port to container port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on: []
